### PR TITLE
fixes issue #129: only check tld if sld exists

### LINKED ISSUE #129: @gm, @gma and @gmai are suggested as @gr
Using the default options any input of

```
name@gm
name@gma
name@gmai
```

is suggested with domain `gr`. Any idea why?

### PR DESCRIPTION
**Pull request by caphun**
fixes #129 by checking tld only if sld exists.

### CODE REVIEW

**Comment by derrickko** [comment]
Can you update the tests? Thanks!

**Comment by caphun** [comment]
@derrickko I added the tests as requested.

I noticed however that the spec has a discrepancy when run caused by specifying gmx.de as one of the domains. Since the Mailcheck plugin does not have that as a defaultDomain, when the test is run via the spec and when it is run through the example/index.html provided the results are different. Additionally gmx also supports .co.uk and .com domains hence it doesn't make sense to use gmx.de as one of the default test cases.

**Comment by caphun** [comment]
@derrickko *bump* 

Let me know if there are any issues stopping this pull request from being merged?

**Comment by derrickko** [comment]
Apologies for the delay. Looks good, can you merge in the latest, and update the PR? 

Side note: We're looking into minimization automation.

**Pull request merged**
