### PR TITLE
Extend unit tests for mailcheck.sift3Distance & mailcheck.suggest

### PR DESCRIPTION
**Pull request by jeroenoomsNL**

### CODE REVIEW

**Comment by weilu** [comment]
sift3Distance is pulled in as an external dependency (I'm aware that copy & paste isn't the best way to manage dependencies) so in principle I don't think it needs to be tested in this library. I don't have strong opinions for/against this PR. @derrickko?

**Comment by jeroenoomsNL** [comment]
As long as it's copy/paste I think it's better to write the tests as complete as possible.

**Comment by weilu** [comment]
The suggested tests merely test the edge cases. If completeness is what you are going for care to make it more comprehensive?

**Comment by jeroenoomsNL** [comment]
Thats true, I needed extra tests for a higher coverage at my own project. So after I did this I thought it nice to share it with the community :-)

**Comment by derrickko** [comment]
Definitely agree with the spirit behind the extra coverage. And as mentioned, the tests were meant to tackle edge cases. The right solution would be to manage the sift3 dependency properly. Until that happens, I'd rather keep the tests algorithm agnostic. Thanks for the PR though!

**Pull request closed without merging**
